name: Android Nightly

on:
  push:
    paths:
      - 'android/**'
      - 'lib/**'
      - 'lang/**'
      - 'fonts/**'
      - 'pubspec*'
      - 'pigeons/**'
      - 'test/**'
      - '.github/workflows/nightly.yml'
jobs:
  build:
    if: github.repository == 'pebble-dev/mobile-app'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: dart pub global activate fvm
      - run: fvm install
      - run: fvm flutter pub get
      - run: fvm flutter analyze --no-fatal-infos
      - name: Flutter test
        continue-on-error: true
        run: fvm flutter test
      - run: fvm flutter build apk --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk
      - name: Upload golden failures
        uses: actions/upload-artifact@v1
        with:
          name: goldens-failures
          path: test/components/failures/
